### ISSUE TITLE
Update version on Open VSX

### ISSUE THREAD

**Issue by jwaggy** [warpnet/vscode-salt-lint#15]
The version on open-vsx.org isn't up to date. I know I would appreciate it if you were to update it for those using vscodium.

**Comment by jbouter** [comment]
Hi @jwaggy! 👋🏻 Thanks for bringing this to our attention. I'll make sure the version is updated soon.

**Comment by roaldnefs** [comment]
The latest `vscode-salt-lint` version was just published to Open VSX, see [`warpnet.salt-lint`](https://open-vsx.org/extension/warpnet/salt-lint)! 🚀 

I've created #16 and #17 to make sure we automate the release to both Open VSX and the VS Code Marketplace.
