### ISSUE TITLE
Error: command 'salt-lint.runLint' not found

### ISSUE THREAD

**Issue by hbokh** [warpnet/vscode-salt-lint#6]
Hello Warpnet!
I installed `salt-lint` as described, using `pip3`. It works fine on the CLI, but this extension gives `command 'salt-lint.runLint' not found` every time I try to run it from the "Command Palette".

Any clues on how to fix or debug this issue?

**Comment by roaldnefs** [comment]
Thanks, @hbokh for your bug report! Does the vscode extension work if you open a `.sls` file with the default settings?

**Comment by hbokh** [comment]
Aha! `.sls`...
I had this set in `settings.json`:

```json
    // Configure file associations to languages (e.g. "*.extension": "html"). These have precedence over the default associations of the languages installed.
    "files.associations": {
        "*.sls": "yaml",
        "*.jinja": "jinja",
    },
```

and upon commenting, it started working as expected.
Since this is a PEBKAC I will close the issue and you can drop the bug label. 👍
