### ISSUE TITLE
Does not work with salt-lint 0.4.0 or newer

### ISSUE THREAD

**Issue by an0nz** [warpnet/vscode-salt-lint#8]
After updating salt-lint to 0.4.0 or 0.4.1 linting errors in VSCode do not appear, by downgrading to 0.3.0 linting issues appear again.

**Comment by an0nz** [comment]
Forgot to mention this is on py2.7 (salt-lint works on the command line still with the new version)

**Comment by jbouter** [comment]
Thanks for your report @an0nz - I can confirm it does not work with py3 either. We'll look into it.

**Comment by yuvmel** [comment]
This seems to have been fixed with salt-lint 0.4.2: https://github.com/warpnet/salt-lint/issues/193

**Comment by hbokh** [comment]
Can confirm this is working again with `salt-lint 0.4.2`.

**Comment by an0nz** [comment]
Can also confirm this issue is resolved in newer releases
